# Generated by Django 4.0.5 on 2022-06-08 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='disponibilidad',
        ),
    ]
