# Generated by Django 4.0.5 on 2022-06-05 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categoriaprod_producto_remove_vehiculo_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriaprod',
            name='created',
        ),
        migrations.RemoveField(
            model_name='categoriaprod',
            name='update',
        ),
    ]
