# Generated by Django 4.0.5 on 2022-06-05 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_categoriaprod_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
