# Generated by Django 4.0.5 on 2022-06-06 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='disponibilidad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
