# Generated by Django 4.0.5 on 2022-06-06 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_producto_disponibilidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
    ]
