# Generated by Django 4.0.5 on 2022-06-06 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_producto_categorias_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
    ]
