# Generated by Django 4.0.5 on 2022-06-06 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_producto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaprod',
            options={},
        ),
    ]
