# Generated by Django 4.0.5 on 2022-06-06 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_categoriaprod_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriaProd',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
