# Generated by Django 4.0.5 on 2022-06-06 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categorias',
        ),
        migrations.DeleteModel(
            name='CategoriaProd',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
